---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: sushiweb
      labels:
        app: sushiweb-rhacm
      namespace: sushiweb-rhacm
    spec:
      selector:
        matchExpressions:
          - key: app
            operator: In 
            values: 
              - sushiweb-rhacm
