---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- velero-restore.yaml
- lets-chat-deployment.yaml
- lets-chat-route.yaml
- lets-chat-svc.yaml
- mongodb-dc.yaml
- mongodb-svc.yaml
- mongodb-pvc.yaml
#- mongodb-pv.yaml
- mongodb-secret.yaml
- velero-schedule-backup.yaml