---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- mongodb-pvc.yaml
- mongodb-dc.yaml
#- namespace.yaml

resources:
#- serviceaccount.yaml
#- rolebinding.yaml
